# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageFlipper' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'JSONModel'
  pod 'SDWebImage', '~>3.8'

  target 'ImageFlipperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
